name: Add Issues to Project

on:
  issues:
    types:
      - opened
      - labeled # Trigger when an issue is opened OR a label is added

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Add to NSpace ERC Project
        uses: actions/add-to-project@v0.5.0 # Use the latest version
        with:
          project-url: "https://github.com/orgs/NSpaceTeam/projects/4"
          github-token: ${{ secrets.NSPACE_PROJECT_AUTOMATION }} # PAT with project scope
          labeled: "bug, feature, task" # Optional: only add if it has one of these labels
          # label-operator: OR # Optional: if multiple labels, use OR or AND
